### PR TITLE
Filter Feed Related Fixes + Frontend Activities Coherence

### LINKED ISSUE #52: Integrate Filter Functionality into RecommendationView
Blocked by #23 right now

### PR DESCRIPTION
**Pull request by helen-li**
# Description

Fixes #52, #29, #36, #34 

Changes relevant to the filter feed use case:
* `currentUser` is now passed around the feed package files correctly
* Fixed null pointers caused by `NoNewRecommendation` and added button for going back to the filter activity
* Updated `RecommendationView` with a button to the filter activity
* Added form validation to make sure the chosen max age is at least as big as the chosen min age in the filter activity
* Added `removeCurrentUser` to `GenerateCompatibilityList` since the older code for removing current user was causing problems with the database
* Fixed `FilterUseCaseUnitTest` which was causing errors due to newly added `User` constructor with uid parameter
* Added `RecommendationFilterInputData` to pass filter inputs more cleanly

Changes relevant to other parts of the project:
* Renamed `Login` to `LoginActivity` and moved it inside the login use case package
* Removed all content related to `HelloWorld` and `appTestWelcomeScreens` to reduce unnecessary clutter
* Created a `Constants` file to store final variables shared by more than 1 file
* Refactored `ucUserReader` method `getUser` by adding Thread
* Some test files are commented out to make GitHub Actions cooperate

Screenshots:
<div>
RecommendationView
NoNewRecommendation
NoNewRecommendation
</div>

# Checklist

- [x] My PR does not contain unrelated files that may cause conflicts
- [x] I have performed a self-review of my own code
- [x] I have commented my code with javadoc and perhaps in-line comments (particularly in
  hard-to-understand areas)
- [x] My changes generate no new warnings or errors
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have not violated clean architecture principles
- [x] I have opted to use the most general form of datastructures (example: use `List` instead of
  `ArrayList` wherever possible)

### CODE REVIEW

**Review by chloe2407 — DISMISSED** [review]
Thanks Helen for making these changes! They are useful to connect all of our different pieces of code together and create a general well-working flow.

**Review by chloe2407 — APPROVED** [review]

File: app/src/main/java/com/group80/uoftinder/entities/Constants.java [hunk 1]
```diff
@@ -0,0 +1,12 @@
+package com.group80.uoftinder.entities;
+
```
Comment (MilenaMijuskovic) [inline app/src/main/java/com/group80/uoftinder/entities/Constants.java:2]: Nice! I think this is really useful for all of us to use.

**Review by MilenaMijuskovic — APPROVED** [review]

**Review by LanceLi1416 — APPROVED** [review]
Looks good! Especially love the `Constants.java` to standardize things. 

For the database, they may need further refinements, but I think they are good for this PR.
